name: needle_orm_migration_generator
description: Generate all orm migration help classes for needle orm.
version: 0.0.1
homepage: https://github.com/outersky/needle_orm_migration_generator.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: '>=2.0.0 <4.0.0'
  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  source_gen: ^1.0.0
  needle_orm: ^0.0.1
  scope: ^2.2.1
  angel3_migration: ^4.0.3
  angel3_orm: ^4.0.3
  angel3_orm_generator: ^4.0.3
  inflection3: ^0.5.3+2
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.0
  test: ^1.5.3

dependency_overrides:
  needle_orm:
    path: ../needle_orm

